baseURL: "https://mercurial2.netlify.app/"
title: "Mercurial, finanzas, mercados y un poco de R"
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Santiago Oberto
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/soberto
    - icon: twitter
      name: Twitter
      url: https://twitter.com/santiago_oberto
